const CATEGORY_PARENT_ROUTES: Record<string, string> = {
  "single-seaters": "sofa",
  "two-seaters": "sofa",
  "three-seaters": "sofa",
  "four-seaters-more": "sofa",
  "corner-sofas": "sofa",
  "sectional-sofas": "sofa",
  "modular-sofas": "sofa",
  "lounge-sofas": "sofa",
  recliners: "sofa",
  "office-sofas": "sofa",
  "upholstered-beds": "beds",
  "wooden-beds": "beds",
  "beds-with-storage": "beds",
  "four-seater-dining-tables": "dining-tables",
  "six-seater-dining-tables": "dining-tables",
  "eight-seater-dining-tables": "dining-tables",
  "childrens-beds": "kids-furniture",
  "study-tables": "kids-furniture",
  "study-chairs": "kids-furniture",
  "outdoor-sofas": "outdoor-furniture",
  "outdoor-chairs": "outdoor-furniture",
  "outdoor-tables": "outdoor-furniture",
  "accent-chairs": "accent-furniture",
  armchairs: "accent-furniture",
  ottomans: "accent-furniture",
  poufs: "accent-furniture",
  benches: "accent-furniture",
  "bean-bags": "accent-furniture",
  "executive-chairs": "office-chairs",
  "lounge-chairs": "office-chairs",
  "workstation-chairs": "office-chairs",
  "visitor-chairs": "office-chairs",
  "training-chairs": "office-chairs",
  "public-seatings": "office-chairs",
  "boss-tables": "office-tables",
  "conference-room-tables": "office-tables",
  worktables: "office-tables",
  "height-adjustable-tables": "office-tables",
  "bed-headboards": "spares",
  "table-bases": "spares",
  "gas-lifts": "spares",
  handles: "spares",
  "chair-bases": "spares",
  "pin-wheels": "spares",
};

export const getProductCategoryPath = (category: string) =>
  `/${CATEGORY_PARENT_ROUTES[category] ?? category}`;

